[package]
name = "wizapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
lazy_static = "1.4.0"
tokio = "1.35.1"
tracing = "0.1.37"
wizrpc = "0.1.7"
